# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# https://devopsjournal.io/blog/2021/12/11/GitHub-Actions-Maturity-Levels

name: Build

on:
  push:
    branches: [ main ]
    tags:
      - "*.*.*"
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  # For the releases
  contents: write

env:
  DOTNET_VERSION: 9.x
  # Disable the .NET logo
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Android keystore signing
  ANDROID_SIGNING_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}

jobs:
  # MAUI Android Build
  build-android:
    name: Android Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: '${{ secrets.AWORKOUTADAY_SSH_KEY }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore Hybrid/Hybrid.csproj

      - name: Build MAUI Android
        run: dotnet publish Hybrid/Hybrid.csproj -c Release -f net9.0-android --no-restore -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=../.a-workout-a-day/aworkoutaday.keystore -p:AndroidSigningKeyAlias=aworkoutaday -p:AndroidSigningKeyPass=env:ANDROID_SIGNING_PASSWORD -p:AndroidSigningStorePass=env:ANDROID_SIGNING_PASSWORD

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android # The name of the artifact container/zip file
          path: Hybrid/bin/Release/net9.0-android/*.apk

  # MAUI Windows Build
  build-windows:
    name: Windows Build
    runs-on: windows-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: '${{ secrets.AWORKOUTADAY_SSH_KEY }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore Hybrid/Hybrid.csproj

      - name: Build MAUI Windows
        run: dotnet publish Hybrid/Hybrid.csproj -c Release -f net9.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows # The name of the artifact container/zip file
          path: Hybrid/bin/Release/net9.0-windows10.0.19041.0/win10-x64/AppPackages/Hybrid*/Hybrid*.msix

  # MAUI iOS Build
  build-ios:
    name: iOS Build
    runs-on: macos-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: '${{ secrets.AWORKOUTADAY_SSH_KEY }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore Hybrid/Hybrid.csproj

      - name: Build MAUI iOS
        run: dotnet build Hybrid/Hybrid.csproj -c Release -f net9.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios # The name of the artifact container/zip file
          path: Hybrid/bin/Release/net9.0-ios/iossimulator-x64/**/*.app

  # MAUI MacCatalyst Build
  build-mac:
    name: MacCatalyst Build
    runs-on: macos-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: '${{ secrets.AWORKOUTADAY_SSH_KEY }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore Hybrid/Hybrid.csproj

      - name: Build MAUI MacCatalyst
        run: dotnet publish Hybrid/Hybrid.csproj -c Release -f net9.0-maccatalyst --no-restore -p:BuildIpa=True

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos # The name of the artifact container/zip file
          path: Hybrid/bin/Release/net9.0-maccatalyst/maccatalyst-x64/publish/*.pkg

  # Release all
  release:
    name: Release
    runs-on: ubuntu-latest
    # Run if previous jobs were successful or skipped
    if: ${{ always() && !failure() && !cancelled() && startsWith(github.ref, 'refs/tags/') }}
    needs: [build-android, build-windows, build-ios, build-mac]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: release_files

      #- name: Display structure of downloaded files
      #  run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/release_files/**/*