# This workflow will test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# https://devopsjournal.io/blog/2021/12/11/GitHub-Actions-Maturity-Levels

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  # set this to the .NET Core version to use
  DOTNET_VERSION: '9.x'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build Core
      run: dotnet build Core.Test/Core.Test.csproj

    - name: Build Data
      run: dotnet build Data.Test/Data.Test.csproj

    - name: Build Api
      run: dotnet build Api.Test/Api.Test.csproj

    - name: Build Web
      run: dotnet build Web.Test/Web.Test.csproj
  
    - name: Add IP address to trusted source (managed database)
      uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@5f3d7fcf203022390271fc5be604eecf47f40868
      with:
        action: "add"
        database_id: ${{ secrets.DATABASE_ID }}
        digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        ConnectionStrings:CoreContext: ${{ secrets.CORE_CONTEXT }}

    - name: Remove IP address to trusted source (managed database)
      # Run this step even if the previous step fails
      if: success() || failure()
      uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@5f3d7fcf203022390271fc5be604eecf47f40868
      with:
        action: "remove"
        database_id: ${{ secrets.DATABASE_ID }}
        digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}